Splitter: 
  energy:
    description: splitter for energy documents 
    expression: |
      WilkenDMSId:\\s?([a-zA-Z0-9.-]*)
    metadata:
      soapUrl: ${env.WKCSREST_ENERGY_URL}
      keyExtractor: |
        <.*#([a-zA-Z0-9.-\\s)(]*).*>
      transformer: 
        documentDescription: 
          creationDate: = $fromMillis($toMillis($now()),"[Y0001]-[M01]-[D01] [H01]:[m01]:[s01]")
          docType: Energy
          filename: = data.dmsDokumentId & ".pdf"
          mimeType: application/pdf
          wilkenID: = data.dmsDokumentId
          location: WILKEN_TWF_VERTRIEB
          properties: 
            - key: VERTRAGSKONTONR
              value: 
                - |
                  = data.Kundennummer
            - key: VERTRAGSKONTONAME 
              value: 
                - |
                  = data.Name & ", " & data.Vorname
            - key: BELEGDATUM 
              value: 
                - |
                  = data.Druckdatum
            - key: BELEGART
              value: 
                - |
                  = data.Kontakttyp
 