Connectors:
  saperion: 
    defaults:
      mapping: 
        fromSaperion: 
          DOCID : wilkenID
          MIMETYPE: MIMETYPE
          MASTERDOCID: MASTERDOCID
          EXTERN_DOC_UNIQUEFILENAME: EXTERN_DOC_UNIQUEFILENAME
          VERTRAGSKONTONR: VERTRAGSKONTONR
          VERTRAGSKONTONAME: VERTRAGSKONTONAME
          BELEGDATUM: BELEGDATUM
          BELEGART: BELEGART
          BELEGNR: BELEGNR
          BELEGBEZEICHNUNG: BELEGBEZEICHNUNG
          BETRAG_BRUTTO: BETRAG_BRUTTO
          ABNAHME_PLZ: ABNAHME_PLZ
          ABNAHME_ORT: ABNAHME_ORT
          ABNAHME_STRASSE: ABNAHME_STRASSE
          ABNAHME_HAUSNR_VON: ABNAHME_HAUSNR_VON
          ABNAHME_HAUSNR_BIS: ABNAHME_HAUSNR_BIS
          ABNAHME_HAUSNR_ZUSATZ_VON: ABNAHME_HAUSNR_ZUSATZ_VON
          ABNAHME_HAUSNR_ZUSATZ_BIS: ABNAHME_HAUSNR_ZUSATZ_BIS
          ZAEHLPUNKTBEZEICHNUNG: ZAEHLPUNKTBEZEICHNUNG
          ZAEHLERNR: ZAEHLERNR
          ABNAHME_NR: ABNAHME_NR
          ABNAHME_NAME: ABNAHME_NAME
          ABNAHME_VORNAME: ABNAHME_VORNAME
          ABNAHME_NAME_ZUSATZ:  ABNAHME_NAME_ZUSATZ
          BELEG_EMPFAENGERNR: BELEG_EMPFAENGERNR
          BELEG_NAME: BELEG_NAME
          BELEG_VORNAME: BELEG_VORNAME
          BELEG_NAME_ZUSATZ:  BELEG_NAME_ZUSATZ
          BELEG_ADRESSE_ZUSATZ: BELEG_ADRESSE_ZUSATZ
          BELEG_PLZ: BELEG_PLZ
          BELEG_ORT: BELEG_ORT
          BELEG_STRASSE: BELEG_STRASSE
          BELEG_HAUSNR_VON: BELEG_HAUSNR_VON
          BELEG_HAUSNR_BIS: BELEG_HAUSNR_BIS
          BELEG_HAUSNR_ZUSATZ_VON: BELEG_HAUSNR_ZUSATZ_VON
          BELEG_HAUSNR_ZUSATZ_BIS: BELEG_HAUSNR_ZUSATZ_BIS
          ABNAHME_GESCHAETSPARTNERNR: ABNAHME_GESCHAETSPARTNERNR
          BELEG_GESCHAETSPARTNERNR: BELEG_GESCHAETSPARTNERNR
          BETRAG_BRUTTO_DEC: BETRAG_BRUTTO_DEC
        toSaperion: 
          MIMETYPE: MIMETYPE
          MASTERDOCID: MASTERDOCID
          EXTERN_DOC_UNIQUEFILENAME: EXTERN_DOC_UNIQUEFILENAME
          VERTRAGSKONTONR: VERTRAGSKONTONR
          VERTRAGSKONTONAME: VERTRAGSKONTONAME
          BELEGDATUM: BELEGDATUM
          BELEGART: BELEGART
          BELEGNR: BELEGNR
          BELEGBEZEICHNUNG: BELEGBEZEICHNUNG
          BETRAG_BRUTTO: BETRAG_BRUTTO
          ABNAHME_PLZ: ABNAHME_PLZ
          ABNAHME_ORT: ABNAHME_ORT
          ABNAHME_STRASSE: ABNAHME_STRASSE
          ABNAHME_HAUSNR_VON: ABNAHME_HAUSNR_VON
          ABNAHME_HAUSNR_BIS: ABNAHME_HAUSNR_BIS
          ABNAHME_HAUSNR_ZUSATZ_VON: ABNAHME_HAUSNR_ZUSATZ_VON
          ABNAHME_HAUSNR_ZUSATZ_BIS: ABNAHME_HAUSNR_ZUSATZ_BIS
          ZAEHLPUNKTBEZEICHNUNG: ZAEHLPUNKTBEZEICHNUNG
          ZAEHLERNR: ZAEHLERNR
          ABNAHME_NR: ABNAHME_NR
          ABNAHME_NAME: ABNAHME_NAME
          ABNAHME_VORNAME: ABNAHME_VORNAME
          ABNAHME_NAME_ZUSATZ:  ABNAHME_NAME_ZUSATZ
          BELEG_EMPFAENGERNR: BELEG_EMPFAENGERNR
          BELEG_NAME: BELEG_NAME
          BELEG_VORNAME: BELEG_VORNAME
          BELEG_NAME_ZUSATZ:  BELEG_NAME_ZUSATZ
          BELEG_ADRESSE_ZUSATZ: BELEG_ADRESSE_ZUSATZ
          BELEG_PLZ: BELEG_PLZ
          BELEG_ORT: BELEG_ORT
          BELEG_STRASSE: BELEG_STRASSE
          BELEG_HAUSNR_VON: BELEG_HAUSNR_VON
          BELEG_HAUSNR_BIS: BELEG_HAUSNR_BIS
          BELEG_HAUSNR_ZUSATZ_VON: BELEG_HAUSNR_ZUSATZ_VON
          BELEG_HAUSNR_ZUSATZ_BIS: BELEG_HAUSNR_ZUSATZ_BIS
          ABNAHME_GESCHAETSPARTNERNR: ABNAHME_GESCHAETSPARTNERNR
          BELEG_GESCHAETSPARTNERNR: BELEG_GESCHAETSPARTNERNR
          BETRAG_BRUTTO_DEC: BETRAG_BRUTTO_DEC

 
