# P5/2 DMS WCS3 Mockservice Tenant Configuration

# tenant 
TENANT_CAPTION: Prod - WKCS REST Adapter

# http port of service
WKCSREST_HTTP_PORT: 6952
WKCSSPLITTER_HTTP_PORT: 6953 

# rest connector type 
WKCSREST_CONNECTOR: windream
WKCSREST_BASEURL: "http://<SERVER>:<PORT>"
WKCSREST_AUTH_USER: "<USER>"
WKCSREST_AUTH_PASSWORD: "<PASSWORD>" 

# energy maintenance service
WKSP_SPLITTER_URL: "http://<ENERGYSERVER>:<ENERGYPORT>"

# extend logging of soap calls
WKCSREST_SOAP_LOG: true 
