# P5/2 DMS WKCS REST Adapter Tenant Configuration

# tenant 
TENANT_CAPTION: Test - WKCS REST Adapter

# http port of service
WKCSREST_HTTP_PORT: 6950
WKCSSPLITTER_HTTP_PORT: 6951 

# rest connector type 
WKCSREST_CONNECTOR: saperion
WKCSREST_BASEURL: 'http://<SERVER>:<PORT>'
WKCSREST_AUTH_APIKEY:  <API-KEY>

# energy maintenance service
WKSP_SPLITTER_URL: "http://<ENERGYSERVER>:<ENERGYPORT>"

# extend logging of soap calls
WKCSREST_SOAP_LOG: true 
