# P5/2 DMS WCS3 Mockservice Tenant Configuration

# tenant 
TENANT_CAPTION: Test - WKCS REST Adapter

# http port of service
WKCSREST_HTTP_PORT: 6951
WKCSSPLITTER_HTTP_PORT: 6952 

# rest connector type 
WKCSREST_CONNECTOR: windream
WKCSREST_BASEURL: 'http://localhost:3000'
WKCSREST_AUTH_BEARER: 1XRYGVx61xAWOJVtt95sIYT8lFBZUoBYfDASBMDdNbeXLQFtN0eHHgue/BShwgx0Dz281Pq2nGvxYxsYq+N+ZSHGm3+v9Qy+HqIuUN3Qvx+Qz6P3tjf2xUUDMNNBs4F4&_z_A0V5ayCQBERg_iP8nq_sWPgilPGKvBsEolQb-HjyHRTPt6iAhENl-spNKGaegiUHHd0aCsyOAXosMgfZ4I5CdBInE5qGg
WKCSREST_D3_REPOSITORYID: 27cc8f0e-c069-5b05-99de-46bc77968723

# extend logging of soap calls
WKCSREST_SOAP_LOG: true 
